[outputs]
home = ["HTML", "RSS", "SITEMAP"]

[mediaTypes]
[mediaTypes."application/xml"]
suffixes = ["xml"]

[outputFormats]
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isPlainText = true
